version: '3.4'

services:
  flaskapi:
    image: flaskapi
    build:
      context: ./app-layer
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  postgres:
    image: "postgres:latest"
    env_file:
      - .env
  web:
    build: ./web
    ports: 
      - "8080:80"


