version: '3.4'

services:
  flaskapi:
    image: flaskapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  postgres:
    image: "postgres:latest"
  web:
    build: ./web
    ports: "8080:80"

